investNext/crm/urls.py
from django.urls import path,include
from .views import *

app_name = 'crm'
urlpatterns = [
	path('',main,name='main'),
	path('export/',export,name='export'),
	path('post-card/<int:in_id>',post_card,name='post_card'),
	path('upload/',upload,name='upload'),
	path('contact/', ContactList.as_view(),name='contact'),
	path('contact-indv/<int:c_id>', indivisual_contact,name='indivisual_contact'),
	path('contact-udate/<int:pk>', ContactUpdate.as_view(),name='ContactUpdate'),
	path('contact-delete/<int:pk>', ContactDelete.as_view(),name='ContactDelete'),
	path('contact-create/', ContactCreate.as_view(),name='ContactCreate'),
]

investNext/investNext/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from crm.views import register

urlpatterns = [
	path('admin11/', admin.site.urls),
	path('register/', register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
	path('',include('crm.urls')),
  ]  

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investNext/templates/components/nav.html
<nav>
	<div class="nav">
		<div class="nav-name">
			<img src="https://ddbdhxog1i1ki.cloudfront.net/web/assets/img/investnext_nav_white_logo.png">
			<h1 class="nav-hover">InvestNext</h1>
		</div>
		<div class="nav-a">
			<div class="nav-shadow">
				<div class="nav-icon">
					<a href="{%url 'crm:main'%}" class="material-icons">home </a><p class="nav-hover">Home</p>
				</div>
			</div>
			<div class="nav-shadow">
				<div class="nav-icon">
					<a href="{%url 'crm:contact'%}" class="material-icons">groups</a><p class="nav-hover">Contacts</p>
				</div>
			</div>
			  {% if user.is_authenticated %}
			 <div class="nav-shadow">
				<div class="nav-icon">
					<a href="{%url 'logout'%}" class="material-icons">exit_to_app</a><p class="nav-hover">LOG OUT</p>
				</div>
			</div>
			{%else%}
			<div class="nav-shadow">
				<div class="nav-icon">
					<a href="{%url 'login'%}" class="material-icons">login</a><p class="nav-hover">LOG IN</p>
				</div>
			</div>
			{%endif%}
		</div>
	</div>
</nav>