investNext/crm/urls.py
from django.urls import path,include
from .views import *

app_name = 'crm'
urlpatterns = [
	path('',main,name='main'),
	path('export/',export,name='export'),
	path('post-card/<int:in_id>',post_card,name='post_card'),
	path('upload/',upload,name='upload'),
	path('contact/', ContactList.as_view(),name='contact'),
	path('contact-indv/<int:c_id>', indivisual_contact,name='indivisual_contact'),
	path('contact-udate/<int:pk>', ContactUpdate.as_view(),name='ContactUpdate'),
	path('contact-delete/<int:pk>', ContactDelete.as_view(),name='ContactDelete'),
	path('contact-create/', ContactCreate.as_view(),name='ContactCreate'),
]

investNext/investNext/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from crm.views import register

urlpatterns = [
	path('admin11/', admin.site.urls),
	path('register/', register, name='register'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
	path('',include('crm.urls')),
  ]  

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investNext/templates/contacts/contact_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="contact-header">
        <div class="contact-items">
            <p class="material-icons">contact_page</p>
            <p>Contacts</p>
        </div>
        <div class="contact-items">
        </div>
        <div class="contact-items">
              {% if user.is_authenticated %}
            <p>Welcome <span class="bl-color">{{ user.username|title }}</span></p>
                {%endif%}
        </div>  
    </div>
    <div class="contact-info">
        <div class="all-contact">
            <button class="bt-sl blue-hover shadow">All contact</button>
            <form action="{% url 'crm:export' %}" method="post">
                {% csrf_token %}
                <button type="submit"class="bt-ss blue-hover shadow">Export</button>
            </form>
        </div>
        <div class="all-contact">
              <form action="{% url 'crm:upload' %}" method="post" enctype="multipart/form-data" >
                {% csrf_token %}
                <button type="submit" class="upload">Upload contact</button>
                <label class="blue-hover material-icons"> get_app
                <input type="file" name="myfile" >
                </label>
              </form>
        </div>
        <div class="all-contact">
            <button class="bt-ss blue-hover shadow">Filter</button>
            <button class="bt-ss blue-hover shadow">Action</button>
            <button class="bt-ss blue-hover shadow" onclick="location.href={% url 'crm:ContactCreate' %}">New</button>
        </div>
    </div>

<div class="contact-content no-hr">
    <div class="users">
       <form  method="POST" class="form-box">
         {% csrf_token %}
         <div class="field">
            <label for='first_name' class="label">First-name:</label>
            <div class="form-input">
                {{form.first_name}}
            </div>
         </div>
         <div class="field">
            <label for='last_name' class="label">Last-name:</label>
            <div class="form-input">
                {{form.last_name}}
            </div>
         </div>
         <div class="field">
            <label for='email' class="label">Email:</label>
            <div class="form-input">
                {{form.email}}
            </div>
         </div>
         <div class="field">
            <label for='address_one' class="label">Address1:</label>
            <div class="form-input">
                {{form.address_one}}
            </div>
         </div>
         <div class="field">
            <label for='address_two' class="label">Address2:</label>
            <div class="form-input">
                {{form.address_two}}
            </div>
         </div>
         <div class="field">
            <label for='city' class="label">City:</label>
            <div class="form-input">
                {{form.city}}
            </div>
         </div>
         <div class="field">
            <label for='state' class="label">State:</label>
            <div class="form-input">
                {{form.state}}
            </div>
         </div>
         <div class="field">
            <label for='code' class="label">Code:</label>
            <div class="form-input">
                {{form.code}}
            </div>
         </div>
         <div class="field">
            <label for='phone_number' class="label">Phone:</label>
            <div class="form-input">
                {{form.phone_number}}
            </div>
         </div>
     <div class="bt-box">
      <button class="form-bt" type="submit">Create New</button>
        </div> 
     </form> 
    </div>
</div>
{% endblock content %}




<!-- 
         <button class="btn btn-outline-info" type="submit">Submit</button>
                <a href="{%url 'crm:contact'%}">Cancel</a> -->

investNext/templates/contacts/contact_list.html
{%extends 'base.html'%}
{%block content%}
	<div class="contact-header">
		<div class="contact-items">
			<p class="material-icons">contact_page</p>
			<p>Contacts</p>
		</div>
		<div class="contact-items">
		</div>
		<div class="contact-items">
			  {% if user.is_authenticated %}
			<p>Welcome <span class="bl-color">{{ user.username|title }}</span></p>
				{%endif%}
		</div>	
	</div>
	<div class="contact-info">
		<div class="all-contact">
			<button class="bt-sl blue-hover shadow">All contact</button>
			<form action="{% url 'crm:export' %}" method="post">
				{% csrf_token %}
				<button type="submit"class="bt-ss blue-hover shadow">Export</button>
 			</form>
		</div>
		<div class="all-contact ">
			 <form action="{% url 'crm:upload' %}" method="post" enctype="multipart/form-data" >
			    {% csrf_token %}
			    <button type="submit" class="upload ">Upload contact</button>
			    <label class="blue-hover material-icons"> get_app
			    <input type="file" name="myfile" >
			    </label>
			  </form>
		</div>
		<div class="all-contact">
			<button class="bt-ss blue-hover shadow">Filter</button>
			<button class="bt-ss blue-hover shadow">Action</button>
			<button class="bt-ss blue-hover shadow" onclick="location.href={% url 'crm:ContactCreate' %}">New</button>
		</div>
	</div>
	<div class="contact-content ">
	{%for contact in object_list%}
			<div class="contact-names blue-hover">
				<a href="{%url 'crm:indivisual_contact' contact.id %}" ><p >{{contact.first_name}} {{contact.last_name}}</p></a>
			</div>
			<div class="contact-more-info blue-hover">
				<p>{{contact.email}}</p>
			</div>
			<div class="contact-more-info blue-hover">
				<p>Registered</p>
			</div>
			<div class="contact-more-info blue-hover">
				<p>No</p>
			</div>
	{%endfor%}
	</div>

{%endblock%}

investNext/templates/contacts/contact_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="contact-header">
        <div class="contact-items">
            <p class="material-icons">contact_page</p>
            <p>Contacts</p>
        </div>
        <div class="contact-items">
        </div>
        <div class="contact-items">
              {% if user.is_authenticated %}
            <p>Welcome <span class="bl-color">{{ user.username|title }}</span></p>
                {%endif%}
        </div>  
    </div>
    <div class="contact-info">
        <div class="all-contact">
            <button class="bt-sl blue-hover shadow">All contact</button>
            <form action="{% url 'crm:export' %}" method="post">
                {% csrf_token %}
                <button type="submit"class="bt-ss blue-hover shadow">Export</button>
            </form>
        </div>
        <div class="all-contact">
              <form action="{% url 'crm:upload' %}" method="post" enctype="multipart/form-data" >
                {% csrf_token %}
                <button type="submit" class="upload">Upload contact</button>
                <label class="blue-hover material-icons"> get_app
                <input type="file" name="myfile" >
                </label>
              </form>
        </div>
        <div class="all-contact">
            <button class="bt-ss blue-hover shadow">Filter</button>
            <button class="bt-ss blue-hover shadow">Action</button>
            <button class="bt-ss blue-hover shadow" onclick="location.href={% url 'crm:ContactCreate' %}">New</button>
        </div>
    </div>

<div class="contact-content no-hr">
    <div class="users ">
       <form  method="POST" class="form-box">
         {% csrf_token %}
         <div class="field">
            <label for='first_name' class="label">First-name:</label>
            <div class="form-input">
                {{form.first_name}}
            </div>
         </div>
         <div class="field">
            <label for='last_name' class="label">Last-name:</label>
            <div class="form-input">
                {{form.last_name}}
            </div>
         </div>
         <div class="field">
            <label for='email' class="label">Email:</label>
            <div class="form-input">
                {{form.email}}
            </div>
         </div>
         <div class="field">
            <label for='address_one' class="label">Address1:</label>
            <div class="form-input">
                {{form.address_one}}
            </div>
         </div>
         <div class="field">
            <label for='address_two' class="label">Address2:</label>
            <div class="form-input">
                {{form.address_two}}
            </div>
         </div>
         <div class="field">
            <label for='city' class="label">City:</label>
            <div class="form-input">
                {{form.city}}
            </div>
         </div>
         <div class="field">
            <label for='state' class="label">State:</label>
            <div class="form-input">
                {{form.state}}
            </div>
         </div>
         <div class="field">
            <label for='code' class="label">Code:</label>
            <div class="form-input">
                {{form.code}}
            </div>
         </div>
         <div class="field">
            <label for='phone_number' class="label">Phone:</label>
            <div class="form-input">
                {{form.phone_number}}
            </div>
         </div>
     <div class="bt-box">
      <button class="form-bt" type="submit">Update</button>
        </div> 
     </form> 
    </div>
</div>

{% endblock content %}

investNext/templates/contacts/contacts_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="contact-header">
        <div class="contact-items">
            <p class="material-icons">contact_page</p>
            <p>Contacts</p>
        </div>
        <div class="contact-items">
        </div>
        <div class="contact-items">
              {% if user.is_authenticated %}
            <p>Welcome <span class="bl-color">{{ user.username|title }}</span></p>
                {%endif%}
        </div>  
    </div>
    <div class="contact-info">
        <div class="all-contact">
            <button class="bt-sl blue-hover shadow">All contact</button>
            <form action="{% url 'crm:export' %}" method="post">
                {% csrf_token %}
                <button type="submit"class="bt-ss blue-hover shadow">Export</button>
            </form>
        </div>
        <div class="all-contact">
              <form action="{% url 'crm:upload' %}" method="post" enctype="multipart/form-data" >
                {% csrf_token %}
                <button type="submit" class="upload">Upload contact</button>
                <label class="blue-hover material-icons"> get_app
                <input type="file" name="myfile" >
                </label>
              </form>
        </div>
        <div class="all-contact">
            <button class="bt-ss blue-hover shadow">Filter</button>
            <button class="bt-ss blue-hover shadow">Action</button>
            <button class="bt-ss blue-hover shadow" onclick="location.href={% url 'crm:ContactCreate' %}">New</button>
        </div>
    </div>
<div class="contact-content no-hr">
    <div class="users field">
        <form method="POST"  class="form-box">
            {% csrf_token %}
               <h2>Do you want to delete this file ({{object.first_name}})?</h2>
            <div class="bt-box">
                <button class="form-bt " type="submit">Delete</button>
                <a href="{%url 'crm:contact'%}" class="field">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

investNext/templates/contacts/indivisual_contact.html
{%extends 'base.html'%}
{%block content%}
	<div class="contact-header">
		<div class="contact-items">
			<p class="material-icons">contact_page</p>
			<p>Contacts</p>
		</div>
		<div class="contact-items">
		</div>
		<div class="contact-items">
			  {% if user.is_authenticated %}
			<p>Welcome <span class="bl-color">{{ user.username|title }}</span></p>
				{%endif%}
		</div>	
	</div>
	<div class="contact-info">
		<div class="all-contact">
			<button class="bt-sl blue-hover shadow">All contact</button>
			<form action="{% url 'crm:export' %}" method="post">
				{% csrf_token %}
				<button type="submit"class="bt-ss blue-hover shadow">Export</button>
 			</form>
		</div>
		<div class="all-contact">
			  <form action="{% url 'crm:upload' %}" method="post" enctype="multipart/form-data" >
			    {% csrf_token %}
			    <button type="submit" class="upload">Upload contact</button>
			    <label class="blue-hover material-icons"> get_app
			    <input type="file" name="myfile" >
			    </label>
			  </form>
		</div>
		<div class="all-contact">
			<button class="bt-ss blue-hover shadow">Filter</button>
			<button class="bt-ss blue-hover shadow">Action</button>
			<button class="bt-ss blue-hover shadow" onclick="location.href={% url 'crm:ContactCreate' %}">New</button>
		</div>
	</div>
	<div class="contact-content no-hr ">
		<div class="contact-card shadow">
			<div class="card-content br-top">
				<h2>{{contact.first_name}}</h2>
				<div>
					<a href="{%url 'crm:ContactDelete' contact.pk%}" class="material-icons blue-hover float-r">delete</a>
					<a href="{%url 'crm:ContactUpdate' contact.pk%}" class="material-icons blue-hover float-r">rate_review</a>
					<a href="{%url 'crm:post_card' contact.pk%}" class="material-icons blue-hover float-r">markunread_mailbox</a>
				</div>
			</div>
			<div class="card-content">
				<h3>About this contact</h3>
			</div>
			<div class="card-content no-hr">
				<h3>Email</h3>
				<p>{{contact.email}}</p>
				<h3>Adddress</h3>
				<p>{{contact.address_one}}</p>
				<p>{{contact.address_two}}</p>
				<p>{{contact.city}},{{contact.state}},{{contact.code}}</p>
				<h3>Phone</h3>
				<p>{{contact.phone_number}}</p>
			</div>
			<div class="card-content no-hr">
			</div>
		</div>
	</div>
</div>

{%endblock%}

investNext/templates/contacts/main.html
{%extends 'base.html'%}
{%block content%}
<div class="main-content">
	<h3>Become a world-class real estate investment firm.
	</h3>
	<p>InvestNext is a modern real estate investment management software that consolidates all of your investment and investor information, enabling you to focus on growing your business and provide best-in-class service to investors.</p>
</div>

<div class="main-section">
	<div class="main-box">
		<span  class="material-icons">monetization_on</span>
		<h2>Fundraise More Effectively</h2>
		<p>Close more deals by centralizing, prioritizing, and automating fundraising activities.</p>
		<button>Grow</button>
	</div>
	<div class="main-box">
		<span  class="material-icons">leaderboard</span>
		<h2>Streamline Your Back-Office</h2>
		<p>Reduce overhead by automating your back-office and reallocate your team's efforts to higher-value activities.</p>
		<button>Optomize</button>
	</div>
	<div class="main-box">
		<span  class="material-icons">table_view</span>
		<h2>Delight Your Investors</h2>
		<p>Instill greater confidence among your partners and investors with institutional-grade communication and reporting.</p>
		<button>Engage</button>
	</div>
</div>

{%endblock%}

investNext/templates/contacts/post_card.html
{%extends 'base.html'%}
{%block content%}
	<div class="contact-header">
		<div class="contact-items">
			<p class="material-icons">contact_page</p>
			<p>Contacts</p>
		</div>
		<div class="contact-items">
		</div>
		<div class="contact-items">
			 {% if user.is_authenticated %}
			<p>Welcome <span class="bl-color">{{ user.username|title }}</span></p>
			{%endif%}
		</div>	
	</div>
	<div class="contact-info">
		<div class="all-contact">
			<button class="bt-sl blue-hover shadow">All contact</button>
			<form action="{% url 'crm:export' %}" method="post">
				{% csrf_token %}
				<button type="submit"class="bt-ss blue-hover shadow">Export</button>
 			</form>
		</div>
		<div class="all-contact ">
			 <form action="{% url 'crm:upload' %}" method="post" enctype="multipart/form-data" >
			    {% csrf_token %}
			    <button type="submit" class="upload ">Upload contact</button>
			    <label class="blue-hover material-icons"> get_app
			    <input type="file" name="myfile" >
			    </label>
			  </form>
		</div>
		<div class="all-contact">
			<button class="bt-ss blue-hover shadow">Filter</button>
			<button class="bt-ss blue-hover shadow">Action</button>
			<button class="bt-ss blue-hover shadow" onclick="location.href={% url 'crm:ContactCreate' %}">New</button>
		</div>
	</div>
	<div class="contact-content ">

{%endblock%}

investNext/templates/contacts/upload.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}